import Link from 'next/link'
import Image from 'next/image'

export const metadata = {
  title: 'Terms of Service · Mizan',
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-parchment font-sans text-ink">
      {/* Nav */}
      <header className="sticky top-0 z-10 bg-parchment/95 backdrop-blur-sm border-b border-gold/15">
        <div className="max-w-3xl mx-auto px-4 h-14 flex items-center">
          <Link href="/" className="flex items-center gap-2.5">
            <Image
              src="/images/mizan-logo.png"
              alt="Mizan"
              width={30}
              height={30}
              className="rounded-full"
              unoptimized
            />
            <span className="font-semibold text-sm tracking-wide text-ink">Mizan</span>
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-12 space-y-10">
        {/* Header */}
        <div className="space-y-2">
          <p className="text-xs uppercase tracking-widest text-gold font-semibold">Legal</p>
          <h1 className="font-playfair text-3xl text-ink">Terms of Service</h1>
          <p className="text-sm text-ink-muted">Last updated: May 2026</p>
        </div>

        <p className="text-sm text-ink-muted leading-relaxed">
          By using Mizan (&ldquo;the Service&rdquo;), you agree to the following terms. Please read
          them carefully. If you do not agree, do not use the Service.
        </p>

        <Section title="1. Description of Service">
          <p>
            Mizan is a web application that uses artificial intelligence to suggest Quran verses
            relevant to situations or feelings described by the user. It is offered free of charge
            and is intended as a spiritual companion tool, not a religious authority.
          </p>
        </Section>

        <Section title="2. AI-Generated Content">
          <p>
            Verse suggestions and connection explanations are generated by an AI model (Anthropic
            Claude). While we instruct the model to return only authentic Quran verses with accurate
            Arabic text and translations, we cannot guarantee the completeness or appropriateness
            of every response.
          </p>
          <p>
            Mizan enriches AI responses with verified data from the Quran Foundation API, but
            you should always cross-reference important religious guidance with a qualified scholar
            or authoritative Quran resource.
          </p>
          <p>
            <strong className="text-ink">Mizan is not a fatwa service and does not provide religious rulings.</strong>
          </p>
        </Section>

        <Section title="3. Acceptable Use">
          <p>You agree not to use Mizan to:</p>
          <ul className="list-disc list-inside space-y-1.5 text-ink-muted">
            <li>Submit content that is abusive, hateful, or harmful</li>
            <li>Attempt to extract, scrape, or abuse the underlying APIs</li>
            <li>Impersonate any person or entity</li>
            <li>Use the Service for any unlawful purpose</li>
            <li>Deliberately attempt to generate blasphemous or offensive outputs</li>
          </ul>
          <p>We reserve the right to block access to the Service for violations of these terms.</p>
        </Section>

        <Section title="4. Intellectual Property">
          <p>
            The Mizan application code is open source under the MIT License, available at{' '}
            <a
              href="https://github.com/alieutech/mizan"
              className="text-gold hover:text-gold-light underline underline-offset-4"
              target="_blank"
              rel="noopener noreferrer"
            >
              github.com/alieutech/mizan
            </a>
            .
          </p>
          <p>
            Quran text, translations, and tafsir are sourced from the Quran Foundation and
            api.quran.com and remain the property of their respective rights holders.
            Audio recitations are provided by QuranCDN and are used under their respective licenses.
          </p>
        </Section>

        <Section title="5. Disclaimer of Warranties">
          <p>
            Mizan is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied.
            We do not warrant that the Service will be uninterrupted, error-free, or free of
            harmful components. Your use of the Service is at your own risk.
          </p>
        </Section>

        <Section title="6. Limitation of Liability">
          <p>
            To the fullest extent permitted by law, Mizan and its contributors shall not be liable
            for any indirect, incidental, special, or consequential damages arising from your use
            of or inability to use the Service, even if advised of the possibility of such damages.
          </p>
        </Section>

        <Section title="7. Third-Party Services">
          <p>
            Mizan relies on third-party APIs including Anthropic, the Quran Foundation, and
            QuranCDN. We are not responsible for the availability, accuracy, or policies of
            these services. Their respective terms and privacy policies apply to their portions
            of the Service.
          </p>
        </Section>

        <Section title="8. Changes to Terms">
          <p>
            We may revise these Terms at any time by updating this page. The &ldquo;Last updated&rdquo;
            date will reflect any changes. Continued use of the Service after changes are posted
            constitutes your acceptance of the revised Terms.
          </p>
        </Section>

        <Section title="9. Contact">
          <p>
            For questions about these Terms, please open an issue on our{' '}
            <a
              href="https://github.com/alieutech/mizan"
              className="text-gold hover:text-gold-light underline underline-offset-4"
              target="_blank"
              rel="noopener noreferrer"
            >
              GitHub repository
            </a>
            .
          </p>
        </Section>

        <div className="pt-6 border-t border-gold/15 flex items-center justify-between text-xs text-ink-muted">
          <span>© 2026 Mizan</span>
          <Link href="/privacy" className="hover:text-gold transition-colors">
            Privacy Policy →
          </Link>
        </div>
      </main>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="font-playfair text-xl text-ink">{title}</h2>
      <div className="space-y-3 text-sm text-ink-muted leading-relaxed [&_strong]:font-semibold">
        {children}
      </div>
    </section>
  )
}
